### ISSUE TITLE
"No shop!" error occurred

### ISSUE THREAD

**Issue by tomijarvi** [shoopio/shoop-wintergear-demo#4]
Hi,

I trying to install Wintergear Demo to my windows platform. When I running the demo it gives me an error "No shop!". What am I missing?

Here's what I did:
1. Git clone shoop-wintergear-demo by using recursive option
2. Execute "python manage.py runserver" 
3. Browse to "http://127.0.0.1:8000/" and I got error "No Shop!"

Error details:
ImproperlyConfigured at /
No shop!
Request Method: GET
Request URL:    http://127.0.0.1:8000/
Django Version: 1.8.2
Exception Type: ImproperlyConfigured
Exception Value:  
No shop!
Exception Location: z:\shoop-wintergear-demo\shoop\shoop\front\middleware.py in _set_shop, line 88
Python Executable:  C:\Python34\python.exe
Python Version: 3.4.3
Python Path:  
['Z:\shoop-wintergear-demo',
 'z:\shoop-wintergear-demo\shoop',
 'C:\WINDOWS\SYSTEM32\python34.zip',
 'C:\Python34\DLLs',
 'C:\Python34\lib',
 'C:\Python34',
 'C:\Python34\lib\site-packages']
Server time:    Tue, 4 Aug 2015 11:19:11 +0000

**Comment by tomijarvi** [comment]
Answering to my own question. I forgot to run shell commands. 

Run shell commands:
pip install -r requirements.txt
python manage.py wintergear_import_demo
npm run build

And then
python manage.py runserver
browse to "http://127.0.0.1:8000/"

It works perfectly!

**Comment by akx** [comment]
Glad you got it working. :) Feel free to ask if you have any other questions or issues.

**Comment by syx-pravin** [comment]
I configured my own settings.py and manage.py to the alternative of shuup_workbench but after starting server I am getting following error

ImproperlyConfigured at /sa/orders/
No such shop is configured


Please help me

**Comment by syx-pravin** [comment]
> I configured my own settings.py and manage.py to the alternative of shuup_workbench but after starting server I am getting following error
> 
> ImproperlyConfigured at /sa/orders/
> No such shop is configured
> 
> Please help me

I resolved this problem by executing following command

[ python manage.py shuup_init ]
